// -----------------------------------------
// Trainer Pokemon.cs
//
// As seen in DeckData_Story.bin from Pokemon XD - Gale of Darkness (USA) region: US
// At offset: 0x3328 (13096)
// Struct length: 0x20 (32) bytes
// Original c struct generated by StarsMMD GoD Tool
// -----------------------------------------



using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Sequential, Pack = 1)]
struct ByteStats
{
    public char hp;         // offset: 0x0 
    public char attack;     // offset: 0x1 
    public char defense;    // offset: 0x2 
    public char spatk;      // offset: 0x3 
    public char spdef;      // offset: 0x4 
    public char speed;      // offset: 0x5 
}

[StructLayout(LayoutKind.Sequential, Pack = 1)]
struct TrainerPokemon
{
    public ushort species;                  // offset: 0x0 
    public char level;                      // offset: 0x2 
    public char happiness;                  // offset: 0x3 
    public ushort item;                     // offset: 0x4 
    public char aiRole;                     // offset: 0x6 
    public char unknown;                    // offset: 0x7 
    public ByteStats ivs;                   // offset: 0x8 
    public ByteStats evs;                   // offset: 0xE 

    [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
    public ushort[] moves;                  // offset: 0x14 

    public char unused;                     // offset: 0x1C 
    public char unknown2;                   // offset: 0x1D 
    public char miniPid;                    // offset: 0x1E 
    public char useRandomNatureAndGender;    // offset: 0x1F 
}
