using System;

namespace GameEditor
{

    [Serializable]
    public class Files //Filelist for XD:GoD
    {
        public int[]? bootbin { get; set; }
        public int[]? bi2bin { get; set; }
        public int[]? fstbin { get; set; }
        public int[]? startdol { get; set; }
        public int[]? appldrbin { get; set; }
        public int[]? auto_demofsys { get; set; }
        public int[]? B1_1fsys { get; set; }
        public int[]? B1_2fsys { get; set; }
        public int[]? B1_3fsys { get; set; }
        public int[]? B1_4fsys { get; set; }
        public int[]? B1_5fsys { get; set; }
        public int[]? B1_6fsys { get; set; }
        public int[]? B1_7fsys { get; set; }
        public int[]? battle_diskfsys { get; set; }
        public int[]? battle_disk_docfsys { get; set; }
        public int[]? battle_disk_doc_frfsys { get; set; }
        public int[]? battle_disk_doc_gefsys { get; set; }
        public int[]? battle_disk_doc_itfsys { get; set; }
        public int[]? battle_disk_doc_spfsys { get; set; }
        public int[]? battle_disk_frfsys { get; set; }
        public int[]? battle_disk_gefsys { get; set; }
        public int[]? battle_disk_itfsys { get; set; }
        public int[]? battle_disk_spfsys { get; set; }
        public int[]? battle_select_menufsys { get; set; }
        public int[]? bg0thumbcodebin { get; set; }
        public int[]? bg1thumbcodebin { get; set; }
        public int[]? bg2thumbcodebin { get; set; }
        public int[]? bgm_archivefsys { get; set; }
        public int[]? bingo_menufsys { get; set; }
        public int[]? bingo_menu_frfsys { get; set; }
        public int[]? bingo_menu_gefsys { get; set; }
        public int[]? bingo_menu_itfsys { get; set; }
        public int[]? bingo_menu_spfsys { get; set; }
        public int[]? bingo_sheetfsys { get; set; }
        public int[]? bingo_sheet_frfsys { get; set; }
        public int[]? bingo_sheet_gefsys { get; set; }
        public int[]? bingo_sheet_itfsys { get; set; }
        public int[]? bingo_sheet_spfsys { get; set; }
        public int[]? camera_shake_datafsys { get; set; }
        public int[]? carde_menufsys { get; set; }
        public int[]? chara_bigfsys { get; set; }
        public int[]? chara_smallfsys { get; set; }
        public int[]? colosseumbattleconnection_menufsys { get; set; }
        public int[]? colosseumbattle_menufsys { get; set; }
        public int[]? commonfsys { get; set; }
        public int[]? common_dvdethfsys { get; set; }
        public int[]? couponbin { get; set; }
        public int[]? D1_garage_1Ffsys { get; set; }
        public int[]? D1_garage_B1fsys { get; set; }
        public int[]? D1_garage_B1_bffsys { get; set; }
        public int[]? D1_garage_B2_1fsys { get; set; }
        public int[]? D1_garage_B2_2fsys { get; set; }
        public int[]? D1_garage_B2_2_ev_1fsys { get; set; }
        public int[]? D1_garage_B2_2_ev_2fsys { get; set; }
        public int[]? D1_labo_1Ffsys { get; set; }
        public int[]? D1_labo_B1fsys { get; set; }
        public int[]? D1_labo_B1_bffsys { get; set; }
        public int[]? D1_labo_B2fsys { get; set; }
        public int[]? D1_labo_B3fsys { get; set; }
        public int[]? D1_outfsys { get; set; }
        public int[]? D1_out_bffsys { get; set; }
        public int[]? D2_cloud_1fsys { get; set; }
        public int[]? D2_cloud_1_bffsys { get; set; }
        public int[]? D2_cloud_2fsys { get; set; }
        public int[]? D2_cloud_3fsys { get; set; }
        public int[]? D2_cloud_4fsys { get; set; }
        public int[]? D2_crater_colofsys { get; set; }
        public int[]? D2_crater_colo_bffsys { get; set; }
        public int[]? D2_magma_1fsys { get; set; }
        public int[]? D2_magma_1_bffsys { get; set; }
        public int[]? D2_magma_2fsys { get; set; }
        public int[]? D2_magma_3fsys { get; set; }
        public int[]? D2_outfsys { get; set; }
        public int[]? D2_out_bffsys { get; set; }
        public int[]? D2_pc_1Ffsys { get; set; }
        public int[]? D2_pc_1F_bffsys { get; set; }
        public int[]? D2_present_roomfsys { get; set; }
        public int[]? D2_rest_1fsys { get; set; }
        public int[]? D2_rest_2fsys { get; set; }
        public int[]? D2_rest_3fsys { get; set; }
        public int[]? D2_rest_4fsys { get; set; }
        public int[]? D2_rest_5fsys { get; set; }
        public int[]? D2_rest_6fsys { get; set; }
        public int[]? D2_rest_7fsys { get; set; }
        public int[]? D2_rest_8fsys { get; set; }
        public int[]? D2_rest_9fsys { get; set; }
        public int[]? D2_valley_1fsys { get; set; }
        public int[]? D2_valley_1_bffsys { get; set; }
        public int[]? D2_valley_2fsys { get; set; }
        public int[]? D2_valley_3fsys { get; set; }
        public int[]? D3_outfsys { get; set; }
        public int[]? D3_ship_B1_1fsys { get; set; }
        public int[]? D3_ship_B1_2fsys { get; set; }
        public int[]? D3_ship_B1_3fsys { get; set; }
        public int[]? D3_ship_B2_1fsys { get; set; }
        public int[]? D3_ship_B2_2fsys { get; set; }
        public int[]? D3_ship_B2_3fsys { get; set; }
        public int[]? D3_ship_bridgefsys { get; set; }
        public int[]? D3_ship_cabinefsys { get; set; }
        public int[]? D3_ship_deckfsys { get; set; }
        public int[]? D3_ship_deck_bffsys { get; set; }
        public int[]? D4_bingo_bffsys { get; set; }
        public int[]? D4_casino_colofsys { get; set; }
        public int[]? D4_casino_colo_bffsys { get; set; }
        public int[]? D4_dome_1fsys { get; set; }
        public int[]? D4_dome_2fsys { get; set; }
        public int[]? D4_dome_2_bffsys { get; set; }
        public int[]? D4_dome_3fsys { get; set; }
        public int[]? D4_dome_4fsys { get; set; }
        public int[]? D4_outfsys { get; set; }
        public int[]? D4_out_2fsys { get; set; }
        public int[]? D4_tower_1F_1fsys { get; set; }
        public int[]? D4_tower_1F_1_bffsys { get; set; }
        public int[]? D4_tower_1F_2fsys { get; set; }
        public int[]? D4_tower_1F_2_bffsys { get; set; }
        public int[]? D4_tower_1F_3fsys { get; set; }
        public int[]? D4_tower_1F_3_bffsys { get; set; }
        public int[]? D4_tower_2F_2_bffsys { get; set; }
        public int[]? D4_tower_2F_bffsys { get; set; }
        public int[]? D5_factory_1Ffsys { get; set; }
        public int[]? D5_factory_1F_bffsys { get; set; }
        public int[]? D5_factory_2Ffsys { get; set; }
        public int[]? D5_factory_3Ffsys { get; set; }
        public int[]? D5_factory_4Ffsys { get; set; }
        public int[]? D5_factory_B1fsys { get; set; }
        public int[]? D5_factory_hatfsys { get; set; }
        public int[]? D5_factory_hat_bffsys { get; set; }
        public int[]? D5_factory_topfsys { get; set; }
        public int[]? D5_factory_top_bffsys { get; set; }
        public int[]? D5_outfsys { get; set; }
        public int[]? D5_out_bffsys { get; set; }
        public int[]? D6_cruiserfsys { get; set; }
        public int[]? D6_dome_1Ffsys { get; set; }
        public int[]? D6_dome_2Ffsys { get; set; }
        public int[]? D6_dome_2F_bffsys { get; set; }
        public int[]? D6_dome_B1fsys { get; set; }
        public int[]? D6_dome_B1_bffsys { get; set; }
        public int[]? D6_fort_1Ffsys { get; set; }
        public int[]? D6_fort_1F_bffsys { get; set; }
        public int[]? D6_fort_2F_1fsys { get; set; }
        public int[]? D6_fort_2F_2fsys { get; set; }
        public int[]? D6_fort_2F_3fsys { get; set; }
        public int[]? D6_fort_3F_1fsys { get; set; }
        public int[]? D6_fort_3F_2fsys { get; set; }
        public int[]? D6_fort_4Ffsys { get; set; }
        public int[]? D6_fort_5Ffsys { get; set; }
        public int[]? D6_fort_6Ffsys { get; set; }
        public int[]? D6_fort_B1fsys { get; set; }
        public int[]? D6_out_allfsys { get; set; }
        public int[]? D6_out_domefsys { get; set; }
        public int[]? D6_out_dome_bffsys { get; set; }
        public int[]? D6_out_footfsys { get; set; }
        public int[]? D6_out_foot_bffsys { get; set; }
        public int[]? D7_outfsys { get; set; }
        public int[]? D7_out_bffsys { get; set; }
        public int[]? debug_menufsys { get; set; }
        public int[]? deck_archivefsys { get; set; }
        public int[]? DNA_keyfsys { get; set; }
        public int[]? eevee_menufsys { get; set; }
        public int[]? ending_eventfsys { get; set; }
        public int[]? ending_Scene01fsys { get; set; }
        public int[]? ending_Scene02fsys { get; set; }
        public int[]? ending_Scene03fsys { get; set; }
        public int[]? ending_Scene04fsys { get; set; }
        public int[]? ending_Scene05_1fsys { get; set; }
        public int[]? ending_Scene05_2fsys { get; set; }
        public int[]? ending_Scene06_1fsys { get; set; }
        public int[]? ending_Scene06_2fsys { get; set; }
        public int[]? ending_Scene06_3fsys { get; set; }
        public int[]? ending_Scene07fsys { get; set; }
        public int[]? ending_Scene08fsys { get; set; }
        public int[]? ending_Scene09fsys { get; set; }
        public int[]? ending_Scene10fsys { get; set; }
        public int[]? ending_Scene11fsys { get; set; }
        public int[]? ending_Scene12_1fsys { get; set; }
        public int[]? ending_Scene12_2fsys { get; set; }
        public int[]? ending_SpecialScene01fsys { get; set; }
        public int[]? ending_SpecialScene02fsys { get; set; }
        public int[]? esaba_Afsys { get; set; }
        public int[]? esaba_A_bffsys { get; set; }
        public int[]? esaba_Bfsys { get; set; }
        public int[]? esaba_B_bffsys { get; set; }
        public int[]? esaba_Cfsys { get; set; }
        public int[]? esaba_C_bffsys { get; set; }
        public int[]? evolutionfsys { get; set; }
        public int[]? ex_couponfsys { get; set; }
        public int[]? ex_shrinefsys { get; set; }
        public int[]? ex_titlefsys { get; set; }
        public int[]? ex_topfsys { get; set; }
        public int[]? field_commonfsys { get; set; }
        public int[]? field_common_frfsys { get; set; }
        public int[]? field_common_gefsys { get; set; }
        public int[]? field_common_itfsys { get; set; }
        public int[]? field_common_spfsys { get; set; }
        public int[]? fight_commonfsys { get; set; }
        public int[]? fight_common_frfsys { get; set; }
        public int[]? fight_common_gefsys { get; set; }
        public int[]? fight_common_itfsys { get; set; }
        public int[]? fight_common_spfsys { get; set; }
        public int[]? fight_demofsys { get; set; }
        public int[]? flashmenufsys { get; set; }
        public int[]? genius_logofsys { get; set; }
        public int[]? GSfsystoc { get; set; }
        public int[]? hologram_menufsys { get; set; }
        public int[]? hologram_menu_afsys { get; set; }
        public int[]? hologram_menu_bfsys { get; set; }
        public int[]? hologram_menu_cfsys { get; set; }
        public int[]? hologram_menu_dfsys { get; set; }
        public int[]? keydiscfsys { get; set; }
        public int[]? M1_carde_1fsys { get; set; }
        public int[]? M1_gym_1Ffsys { get; set; }
        public int[]? M1_gym_1F_bffsys { get; set; }
        public int[]? M1_gym_B1fsys { get; set; }
        public int[]? M1_houseA_1Ffsys { get; set; }
        public int[]? M1_houseA_1F_bffsys { get; set; }
        public int[]? M1_houseA_2Ffsys { get; set; }
        public int[]? M1_houseB_1Ffsys { get; set; }
        public int[]? M1_houseC_1Ffsys { get; set; }
        public int[]? M1_outfsys { get; set; }
        public int[]? M1_out_bffsys { get; set; }
        public int[]? M1_pc_1Ffsys { get; set; }
        public int[]? M1_pc_B1fsys { get; set; }
        public int[]? M1_shop_1Ffsys { get; set; }
        public int[]? M1_shop_2Ffsys { get; set; }
        public int[]? M1_stadium_1Ffsys { get; set; }
        public int[]? M1_water_colofsys { get; set; }
        public int[]? M1_water_colo_bffsys { get; set; }
        public int[]? M1_water_colo_fieldfsys { get; set; }
        public int[]? M2_building_1Ffsys { get; set; }
        public int[]? M2_building_1F_bffsys { get; set; }
        public int[]? M2_building_2Ffsys { get; set; }
        public int[]? M2_building_3Ffsys { get; set; }
        public int[]? M2_building_4Ffsys { get; set; }
        public int[]? M2_cave_1F_1fsys { get; set; }
        public int[]? M2_cave_1F_2fsys { get; set; }
        public int[]? M2_cave_2F_1fsys { get; set; }
        public int[]? M2_cave_2F_2fsys { get; set; }
        public int[]? M2_cave_3F_1fsys { get; set; }
        public int[]? M2_cave_3F_1_bffsys { get; set; }
        public int[]? M2_cave_3F_2fsys { get; set; }
        public int[]? M2_earth_colofsys { get; set; }
        public int[]? M2_enter_1Ffsys { get; set; }
        public int[]? M2_enter_1F_2fsys { get; set; }
        public int[]? M2_guild_1F_1fsys { get; set; }
        public int[]? M2_guild_1F_2fsys { get; set; }
        public int[]? M2_hotel_1Ffsys { get; set; }
        public int[]? M2_houseA_1Ffsys { get; set; }
        public int[]? M2_outfsys { get; set; }
        public int[]? M2_out_bffsys { get; set; }
        public int[]? M2_police_1Ffsys { get; set; }
        public int[]? M2_shop_1Ffsys { get; set; }
        public int[]? M2_uranai_1Ffsys { get; set; }
        public int[]? M2_windmill_1Ffsys { get; set; }
        public int[]? M3_cave_1F_1fsys { get; set; }
        public int[]? M3_cave_1F_1_bffsys { get; set; }
        public int[]? M3_cave_1F_2fsys { get; set; }
        public int[]? M3_houseA_1Ffsys { get; set; }
        public int[]? M3_houseB_1Ffsys { get; set; }
        public int[]? M3_houseC_1Ffsys { get; set; }
        public int[]? M3_houseC_2Ffsys { get; set; }
        public int[]? M3_houseD_1Ffsys { get; set; }
        public int[]? M3_outfsys { get; set; }
        public int[]? M3_out_bffsys { get; set; }
        public int[]? M3_pc_1Ffsys { get; set; }
        public int[]? M3_shop_1Ffsys { get; set; }
        public int[]? M3_shrine_1Ffsys { get; set; }
        public int[]? M3_shrine_1F_bffsys { get; set; }
        public int[]? M3_shrine_1F_rlfsys { get; set; }
        public int[]? M5_apart_1Ffsys { get; set; }
        public int[]? M5_apart_2Ffsys { get; set; }
        public int[]? M5_labo_1Ffsys { get; set; }
        public int[]? M5_labo_2Ffsys { get; set; }
        public int[]? M5_labo_B1fsys { get; set; }
        public int[]? M5_labo_bffsys { get; set; }
        public int[]? M5_outfsys { get; set; }
        public int[]? M5_out_bffsys { get; set; }
        public int[]? M6_crab_1Ffsys { get; set; }
        public int[]? M6_crab_2Ffsys { get; set; }
        public int[]? M6_crab_B1fsys { get; set; }
        public int[]? M6_houseAfsys { get; set; }
        public int[]? M6_houseBfsys { get; set; }
        public int[]? M6_houseCfsys { get; set; }
        public int[]? M6_houseDfsys { get; set; }
        public int[]? M6_junk_1Ffsys { get; set; }
        public int[]? M6_junk_2Ffsys { get; set; }
        public int[]? M6_outfsys { get; set; }
        public int[]? M6_out_bffsys { get; set; }
        public int[]? M6_pc_1Ffsys { get; set; }
        public int[]? M6_pc_2Ffsys { get; set; }
        public int[]? M6_shop_1Ffsys { get; set; }
        public int[]? M6_shop_2Ffsys { get; set; }
        public int[]? M6_tower_1Ffsys { get; set; }
        public int[]? M6_tower_2Ffsys { get; set; }
        public int[]? M6_tower_3Ffsys { get; set; }
        public int[]? M6_tower_4Ffsys { get; set; }
        public int[]? M6_tower_topfsys { get; set; }
        public int[]? M6_tower_top_bffsys { get; set; }
        public int[]? mail000fsys { get; set; }
        public int[]? mail001fsys { get; set; }
        public int[]? mail002fsys { get; set; }
        public int[]? mailopen_menufsys { get; set; }
        public int[]? mailopen_menu_frfsys { get; set; }
        public int[]? mailopen_menu_gefsys { get; set; }
        public int[]? mailopen_menu_itfsys { get; set; }
        public int[]? mailopen_menu_spfsys { get; set; }
        public int[]? maxbtlbin { get; set; }
        public int[]? maxbtl_englishbin { get; set; }
        public int[]? maxbtl_francebin { get; set; }
        public int[]? maxbtl_germanybin { get; set; }
        public int[]? maxbtl_italybin { get; set; }
        public int[]? maxbtl_spainbin { get; set; }
        public int[]? maxcngbin { get; set; }
        public int[]? maxcng_englishbin { get; set; }
        public int[]? maxcng_francebin { get; set; }
        public int[]? maxcng_germanybin { get; set; }
        public int[]? maxcng_italybin { get; set; }
        public int[]? maxcng_spainbin { get; set; }
        public int[]? mechkyogre_movedemofsys { get; set; }
        public int[]? menu_commonfsys { get; set; }
        public int[]? mewwazafsys { get; set; }
        public int[]? pkx_laplacefsys { get; set; }
        public int[]? pkx_latiasfsys { get; set; }
        public int[]? pkx_latiosfsys { get; set; }
        public int[]? pkx_lilylafsys { get; set; }
        public int[]? pkx_livoltfsys { get; set; }
        public int[]? pkx_lizardofsys { get; set; }
        public int[]? pkx_lizardonfsys { get; set; }
        public int[]? pkx_logan_0101fsys { get; set; }
        public int[]? pkx_lovecusfsys { get; set; }
        public int[]? pkx_luckyfsys { get; set; }
        public int[]? pkx_lugiafsys { get; set; }
        public int[]? pkx_lunatonefsys { get; set; }
        public int[]? pkx_madatsubomifsys { get; set; }
        public int[]? pkx_magcargotfsys { get; set; }
        public int[]? pkx_mage_0101fsys { get; set; }
        public int[]? pkx_magmagfsys { get; set; }
        public int[]? pkx_magmarashifsys { get; set; }
        public int[]? pkx_makunoshitafsys { get; set; }
        public int[]? pkx_mania_a1fsys { get; set; }
        public int[]? pkx_mankeyfsys { get; set; }
        public int[]? pkx_mantainfsys { get; set; }
        public int[]? pkx_marilfsys { get; set; }
        public int[]? pkx_marillifsys { get; set; }
        public int[]? pkx_maruminefsys { get; set; }
        public int[]? pkx_marunoomfsys { get; set; }
        public int[]? pkx_massugumafsys { get; set; }
        public int[]? pkx_matadogasfsys { get; set; }
        public int[]? pkx_mayuldfsys { get; set; }
        public int[]? pkx_mcgroudon_1101fsys { get; set; }
        public int[]? pkx_meganiumfsys { get; set; }
        public int[]? pkx_menokuragefsys { get; set; }
        public int[]? pkx_merriepfsys { get; set; }
        public int[]? pkx_metagrossfsys { get; set; }
        public int[]? pkx_metamonfsys { get; set; }
        public int[]? pkx_metangfsys { get; set; }
        public int[]? pkx_mewfsys { get; set; }
        public int[]? pkx_mewtwofsys { get; set; }
        public int[]? pkx_migawarifsys { get; set; }
        public int[]? pkx_milokarossfsys { get; set; }
        public int[]? pkx_miltankfsys { get; set; }
        public int[]? pkx_miniryufsys { get; set; }
        public int[]? pkx_minunfsys { get; set; }
        public int[]? pkx_mirrabo_0101fsys { get; set; }
        public int[]? pkx_mizugoroufsys { get; set; }
        public int[]? pkx_mokokofsys { get; set; }
        public int[]? pkx_monjarafsys { get; set; }
        public int[]? pkx_morphonfsys { get; set; }
        public int[]? pkx_muchulfsys { get; set; }
        public int[]? pkx_mumafsys { get; set; }
        public int[]? pkx_namakerofsys { get; set; }
        public int[]? pkx_namazunfsys { get; set; }
        public int[]? pkx_nassyfsys { get; set; }
        public int[]? pkx_natiofsys { get; set; }
        public int[]? pkx_natyfsys { get; set; }
        public int[]? pkx_nazonokusafsys { get; set; }
        public int[]? pkx_nendollfsys { get; set; }
        public int[]? pkx_nidokingfsys { get; set; }
        public int[]? pkx_nidoqueenfsys { get; set; }
        public int[]? pkx_nidoran_ffsys { get; set; }
        public int[]? pkx_nidoran_mfsys { get; set; }
        public int[]? pkx_nidorinafsys { get; set; }
        public int[]? pkx_nidorinofsys { get; set; }
        public int[]? pkx_niku_f_0101fsys { get; set; }
        public int[]? pkx_niku_f_a1fsys { get; set; }
        public int[]? pkx_niku_m_0101fsys { get; set; }
        public int[]? pkx_niku_m_1101fsys { get; set; }
        public int[]? pkx_niku_m_a1fsys { get; set; }
        public int[]? pkx_niku_m_a2fsys { get; set; }
        public int[]? pkx_niku_m_a3fsys { get; set; }
        public int[]? pkx_niku_m_a4fsys { get; set; }
        public int[]? pkx_noctusfsys { get; set; }
        public int[]? pkx_nokocchifsys { get; set; }
        public int[]? pkx_nosepassfsys { get; set; }
        public int[]? pkx_nuckrarfsys { get; set; }
        public int[]? pkx_nukeninfsys { get; set; }
        public int[]? pkx_numacrawfsys { get; set; }
        public int[]? pkx_nuohfsys { get; set; }
        public int[]? pkx_nyarthfsys { get; set; }
        public int[]? pkx_nyorobonfsys { get; set; }
        public int[]? pkx_nyoromofsys { get; set; }
        public int[]? pkx_nyorotonofsys { get; set; }
        public int[]? pkx_nyorozofsys { get; set; }
        public int[]? pkx_nyulafsys { get; set; }
        public int[]? pkx_obo_a1fsys { get; set; }
        public int[]? pkx_obo_a4fsys { get; set; }
        public int[]? pkx_odoshishifsys { get; set; }
        public int[]? pkx_ohsubamefsys { get; set; }
        public int[]? pkx_ojisan1_0101fsys { get; set; }
        public int[]? pkx_ojisan_a1fsys { get; set; }
        public int[]? pkx_ojo_a1fsys { get; set; }
        public int[]? pkx_ojo_a4fsys { get; set; }
        public int[]? pkx_okorizarufsys { get; set; }
        public int[]? pkx_okutankfsys { get; set; }
        public int[]? pkx_omnitefsys { get; set; }
        public int[]? pkx_omstarfsys { get; set; }
        public int[]? pkx_onidrillfsys { get; set; }
        public int[]? pkx_onigohrifsys { get; set; }
        public int[]? pkx_onisuzumefsys { get; set; }
        public int[]? pkx_ootachifsys { get; set; }
        public int[]? pkx_ordilefsys { get; set; }
        public int[]? pkx_otachifsys { get; set; }
        public int[]? pkx_parasfsys { get; set; }
        public int[]? pkx_parasectfsys { get; set; }
        public int[]? pkx_parshenfsys { get; set; }
        public int[]? pkx_patcheelfsys { get; set; }
        public int[]? pkx_pawoufsys { get; set; }
        public int[]? pkx_pearlulufsys { get; set; }
        public int[]? pkx_pelipperfsys { get; set; }
        public int[]? pkx_persianfsys { get; set; }
        public int[]? pkx_pichufsys { get; set; }
        public int[]? pkx_pigeonfsys { get; set; }
        public int[]? pkx_pigeotfsys { get; set; }
        public int[]? pkx_pikachufsys { get; set; }
        public int[]? pkx_pippifsys { get; set; }
        public int[]? pkx_pixyfsys { get; set; }
        public int[]? pkx_pochienafsys { get; set; }
        public int[]? pkx_ponytafsys { get; set; }
        public int[]? pkx_popoccofsys { get; set; }
        public int[]? pkx_poppofsys { get; set; }
        public int[]? pkx_porygonfsys { get; set; }
        public int[]? pkx_porygon2fsys { get; set; }
        public int[]? pkx_powalenfsys { get; set; }
        public int[]? pkx_powalen_ffsys { get; set; }
        public int[]? pkx_powalen_ifsys { get; set; }
        public int[]? pkx_powalen_wfsys { get; set; }
        public int[]? pkx_praslefsys { get; set; }
        public int[]? pkx_pterafsys { get; set; }
        public int[]? pkx_pukurinfsys { get; set; }
        public int[]? pkx_pupurinfsys { get; set; }
        public int[]? pkx_purinfsys { get; set; }
        public int[]? pkx_pyfsys { get; set; }
        public int[]? pkx_raichufsys { get; set; }
        public int[]? pkx_raikoufsys { get; set; }
        public int[]? pkx_rakuraifsys { get; set; }
        public int[]? pkx_raltsfsys { get; set; }
        public int[]? pkx_rarecoilfsys { get; set; }
        public int[]? pkx_rare_achamofsys { get; set; }
        public int[]? pkx_rare_bakphoonfsys { get; set; }
        public int[]? pkx_rare_bursyamofsys { get; set; }
        public int[]? pkx_rare_cerebifsys { get; set; }
        public int[]? pkx_rare_deoxysfsys { get; set; }
        public int[]? pkx_rare_enteifsys { get; set; }
        public int[]? pkx_rare_firefsys { get; set; }
        public int[]? pkx_rare_freezerfsys { get; set; }
        public int[]? pkx_rare_fushigibanafsys { get; set; }
        public int[]? pkx_rare_groudonfsys { get; set; }
        public int[]? pkx_rare_gyaradosfsys { get; set; }
        public int[]? pkx_rare_hououfsys { get; set; }
        public int[]? pkx_rare_jirachifsys { get; set; }
        public int[]? pkx_rare_jukainfsys { get; set; }
        public int[]? pkx_rare_juptilefsys { get; set; }
        public int[]? pkx_rare_kamexfsys { get; set; }
        public int[]? pkx_rare_kimorifsys { get; set; }
        public int[]? pkx_rare_kyogrefsys { get; set; }
        public int[]? pkx_rare_laglargefsys { get; set; }
        public int[]? pkx_rare_latiasfsys { get; set; }
        public int[]? pkx_rare_latiosfsys { get; set; }
        public int[]? pkx_rare_lizardonfsys { get; set; }
        public int[]? pkx_rare_lugiafsys { get; set; }
        public int[]? pkx_rare_meganiumfsys { get; set; }
        public int[]? pkx_rare_mewfsys { get; set; }
        public int[]? pkx_rare_mewtwofsys { get; set; }
        public int[]? pkx_rare_mizugoroufsys { get; set; }
        public int[]? pkx_rare_numacrawfsys { get; set; }
        public int[]? pkx_rare_ordilefsys { get; set; }
        public int[]? pkx_rare_raikoufsys { get; set; }
        public int[]? pkx_rare_rayquazafsys { get; set; }
        public int[]? pkx_rare_suikunfsys { get; set; }
        public int[]? pkx_rare_thunderfsys { get; set; }
        public int[]? pkx_rare_wakasyamofsys { get; set; }
        public int[]? pkx_rare_yorunozukufsys { get; set; }
        public int[]? pkx_rattafsys { get; set; }
        public int[]? pkx_rayquazafsys { get; set; }
        public int[]? pkx_redianfsys { get; set; }
        public int[]? pkx_redibafsys { get; set; }
        public int[]? pkx_regicefsys { get; set; }
        public int[]? pkx_regirockfsys { get; set; }
        public int[]? pkx_registeelfsys { get; set; }
        public int[]? pkx_research2_0101fsys { get; set; }
        public int[]? pkx_rider_f_a1fsys { get; set; }
        public int[]? pkx_rider_m_0101fsys { get; set; }
        public int[]? pkx_rider_m_a1fsys { get; set; }
        public int[]? pkx_rider_m_a2fsys { get; set; }
        public int[]? pkx_ringumafsys { get; set; }
        public int[]? pkx_rinto_0101fsys { get; set; }
        public int[]? pkx_rinto_1101fsys { get; set; }
        public int[]? pkx_rinto_1102fsys { get; set; }
        public int[]? pkx_rinto_2101fsys { get; set; }
        public int[]? pkx_rinto_2102fsys { get; set; }
        public int[]? pkx_rokonfsys { get; set; }
        public int[]? pkx_roseliafsys { get; set; }
        public int[]? pkx_rougelafsys { get; set; }
        public int[]? pkx_ruffresiafsys { get; set; }
        public int[]? pkx_runpappafsys { get; set; }
        public int[]? pkx_ruririfsys { get; set; }
        public int[]? pkx_saboneafsys { get; set; }
        public int[]? pkx_sailor1_0101fsys { get; set; }
        public int[]? pkx_sailor2_0101fsys { get; set; }
        public int[]? pkx_sailor2_1101fsys { get; set; }
        public int[]? pkx_sakurabyssfsys { get; set; }
        public int[]? pkx_samayourufsys { get; set; }
        public int[]? pkx_samehaderfsys { get; set; }
        public int[]? pkx_sanagirasfsys { get; set; }
        public int[]? pkx_sandfsys { get; set; }
        public int[]? pkx_sandpanfsys { get; set; }
        public int[]? pkx_sawamularfsys { get; set; }
        public int[]? pkx_seadrafsys { get; set; }
        public int[]? pkx_seigi_0101fsys { get; set; }
        public int[]? pkx_sensei_a1fsys { get; set; }
        public int[]? pkx_shellderfsys { get; set; }
        public int[]? pkx_shizarigerfsys { get; set; }
        public int[]? pkx_showersfsys { get; set; }
        public int[]? pkx_sidonfsys { get; set; }
        public int[]? pkx_sihornfsys { get; set; }
        public int[]? pkx_sirnightfsys { get; set; }
        public int[]? pkx_sityo_a1fsys { get; set; }
        public int[]? pkx_sleepefsys { get; set; }
        public int[]? pkx_sleeperfsys { get; set; }
        public int[]? pkx_snach_zako_a1fsys { get; set; }
        public int[]? pkx_snach_zako_a2fsys { get; set; }
        public int[]? pkx_snach_zako_a3fsys { get; set; }
        public int[]? pkx_snatchdan_0101fsys { get; set; }
        public int[]? pkx_snatchdan_1101fsys { get; set; }
        public int[]? pkx_sohnanofsys { get; set; }
        public int[]? pkx_solrockfsys { get; set; }
        public int[]? pkx_sonansfsys { get; set; }
        public int[]? pkx_spearfsys { get; set; }
        public int[]? pkx_sport_f_a1fsys { get; set; }
        public int[]? pkx_sport_m_a1fsys { get; set; }
        public int[]? pkx_starmiefsys { get; set; }
        public int[]? pkx_strikefsys { get; set; }
        public int[]? pkx_subamefsys { get; set; }
        public int[]? pkx_suikunfsys { get; set; }
        public int[]? pkx_sunnygofsys { get; set; }
        public int[]? pkx_syotyou_a1fsys { get; set; }
        public int[]? pkx_tamatamafsys { get; set; }
        public int[]? pkx_tamazarashifsys { get; set; }
        public int[]? pkx_tanebohfsys { get; set; }
        public int[]? pkx_tatsubayfsys { get; set; }
        public int[]? pkx_tattufsys { get; set; }
        public int[]? pkx_tekkaninfsys { get; set; }
        public int[]? pkx_teppouofsys { get; set; }
        public int[]? pkx_tessla_0101fsys { get; set; }
        public int[]? pkx_thief_f_0101fsys { get; set; }
        public int[]? pkx_thief_f_1101fsys { get; set; }
        public int[]? pkx_thief_f_a1fsys { get; set; }
        public int[]? pkx_thief_f_a2fsys { get; set; }
        public int[]? pkx_thief_m_0101fsys { get; set; }
        public int[]? pkx_thief_m_1101fsys { get; set; }
        public int[]? pkx_thief_m_a1fsys { get; set; }
        public int[]? pkx_thief_m_a2fsys { get; set; }
        public int[]? pkx_thief_m_a3fsys { get; set; }
        public int[]? pkx_thunderfsys { get; set; }
        public int[]? pkx_thundersfsys { get; set; }
        public int[]? pkx_todogglerfsys { get; set; }
        public int[]? pkx_todoserugafsys { get; set; }
        public int[]? pkx_togechickfsys { get; set; }
        public int[]? pkx_togepyfsys { get; set; }
        public int[]? pkx_tosakintofsys { get; set; }
        public int[]? pkx_trainer_f_0101fsys { get; set; }
        public int[]? pkx_trainer_m_0101fsys { get; set; }
        public int[]? pkx_traner_f_a1fsys { get; set; }
        public int[]? pkx_traner_m_a1fsys { get; set; }
        public int[]? pkx_transelfsys { get; set; }
        public int[]? pkx_tropiusfsys { get; set; }
        public int[]? pkx_tsubotsubofsys { get; set; }
        public int[]? pkx_tutininfsys { get; set; }
        public int[]? pkx_tyltalisfsys { get; set; }
        public int[]? pkx_tylttofsys { get; set; }
        public int[]? pkx_unknown_afsys { get; set; }
        public int[]? pkx_unknown_bfsys { get; set; }
        public int[]? pkx_unknown_cfsys { get; set; }
        public int[]? pkx_unknown_dfsys { get; set; }
        public int[]? pkx_unknown_efsys { get; set; }
        public int[]? pkx_unknown_exfsys { get; set; }
        public int[]? pkx_unknown_ffsys { get; set; }
        public int[]? pkx_unknown_gfsys { get; set; }
        public int[]? pkx_unknown_hfsys { get; set; }
        public int[]? pkx_unknown_ifsys { get; set; }
        public int[]? pkx_unknown_jfsys { get; set; }
        public int[]? pkx_unknown_kfsys { get; set; }
        public int[]? pkx_unknown_lfsys { get; set; }
        public int[]? pkx_unknown_mfsys { get; set; }
        public int[]? pkx_unknown_nfsys { get; set; }
        public int[]? pkx_unknown_ofsys { get; set; }
        public int[]? pkx_unknown_pfsys { get; set; }
        public int[]? pkx_unknown_qfsys { get; set; }
        public int[]? pkx_unknown_qufsys { get; set; }
        public int[]? pkx_unknown_rfsys { get; set; }
        public int[]? pkx_unknown_sfsys { get; set; }
        public int[]? pkx_unknown_tfsys { get; set; }
        public int[]? pkx_unknown_ufsys { get; set; }
        public int[]? pkx_unknown_vfsys { get; set; }
        public int[]? pkx_unknown_wfsys { get; set; }
        public int[]? pkx_unknown_xfsys { get; set; }
        public int[]? pkx_unknown_yfsys { get; set; }
        public int[]? pkx_unknown_zfsys { get; set; }
        public int[]? pkx_upahfsys { get; set; }
        public int[]? pkx_urimoofsys { get; set; }
        public int[]? pkx_usohachifsys { get; set; }
        public int[]? pkx_usokkiefsys { get; set; }
        public int[]? pkx_utsubotfsys { get; set; }
        public int[]? pkx_utsudonfsys { get; set; }
        public int[]? pkx_vibravafsys { get; set; }
        public int[]? pkx_wakasyamofsys { get; set; }
        public int[]? pkx_waninokofsys { get; set; }
        public int[]? pkx_wanrikyfsys { get; set; }
        public int[]? pkx_warugaki_a1fsys { get; set; }
        public int[]? pkx_wataccofsys { get; set; }
        public int[]? pkx_wazzle_0101fsys { get; set; }
        public int[]? pkx_whalohfsys { get; set; }
        public int[]? pkx_willy_0101fsys { get; set; }
        public int[]? pkx_windiefsys { get; set; }
        public int[]? pkx_worker_0101fsys { get; set; }
        public int[]? pkx_worker_m_a1fsys { get; set; }
        public int[]? pkx_yadokingfsys { get; set; }
        public int[]? pkx_yadonfsys { get; set; }
        public int[]? pkx_yadoranfsys { get; set; }
        public int[]? pkx_yajilonfsys { get; set; }
        public int[]? pkx_yamikarasufsys { get; set; }
        public int[]? pkx_yamiramifsys { get; set; }
        public int[]? pkx_yanyanmafsys { get; set; }
        public int[]? pkx_yarukimonofsys { get; set; }
        public int[]? pkx_yogirasfsys { get; set; }
        public int[]? pkx_yomawarufsys { get; set; }
        public int[]? pkx_yorunozukufsys { get; set; }
        public int[]? pkx_yukiwarashifsys { get; set; }
        public int[]? pkx_yungererfsys { get; set; }
        public int[]? pkx_yuradlefsys { get; set; }
        public int[]? pkx_zangoosefsys { get; set; }
        public int[]? pkx_zenigamefsys { get; set; }
        public int[]? pkx_ziguzagumafsys { get; set; }
        public int[]? pkx_zubatfsys { get; set; }
        public int[]? pocket_menufsys { get; set; }
        public int[]? pokecoupon_menufsys { get; set; }
        public int[]? pokemonchange_menufsys { get; set; }
        public int[]? pokemon_logofsys { get; set; }
        public int[]? poke_bodyfsys { get; set; }
        public int[]? poke_dancefsys { get; set; }
        public int[]? poke_facefsys { get; set; }
        public int[]? prog_memcardfsys { get; set; }
        public int[]? relivehall_menufsys { get; set; }
        public int[]? S1_outfsys { get; set; }
        public int[]? S1_out_bffsys { get; set; }
        public int[]? S1_shop_1Ffsys { get; set; }
        public int[]? S2_bossroom_1fsys { get; set; }
        public int[]? S2_building_1F_2fsys { get; set; }
        public int[]? S2_building_1F_2_bffsys { get; set; }
        public int[]? S2_building_2F_2fsys { get; set; }
        public int[]? S2_building_3F_2fsys { get; set; }
        public int[]? S2_hallway_1fsys { get; set; }
        public int[]? S2_out_1fsys { get; set; }
        public int[]? S2_out_2fsys { get; set; }
        public int[]? S2_out_3fsys { get; set; }
        public int[]? S2_snatchroom_1fsys { get; set; }
        public int[]? S3_labo_1Ffsys { get; set; }
        public int[]? S3_labo_1F_EHfsys { get; set; }
        public int[]? S3_labo_B1lowfsys { get; set; }
        public int[]? S3_labo_B1upfsys { get; set; }
        public int[]? S3_outfsys { get; set; }
        public int[]? S3_out_bffsys { get; set; }
        public int[]? save_menufsys { get; set; }
        public int[]? Script_testfsys { get; set; }
        public int[]? soundsnd_music_atmossamp { get; set; }
        public int[]? soundsnd_sesamp { get; set; }
        public int[]? soundsnd_se_battlesamp { get; set; }
        public int[]? wzx_nenriki_tamatamafsys { get; set; }
        public int[]? wzx_neoharu_sp1fsys { get; set; }
        public int[]? wzx_neoharu_specialfsys { get; set; }
        public int[]? wzx_neoharu_statusfsys { get; set; }
        public int[]? wzx_neppuu_attackfsys { get; set; }
        public int[]? wzx_neppuu_damagefsys { get; set; }
        public int[]? wzx_neppuu_windiefsys { get; set; }
        public int[]? wzx_nestball_downinfsys { get; set; }
        public int[]? wzx_nestball_infsys { get; set; }
        public int[]? wzx_nestball_openfsys { get; set; }
        public int[]? wzx_nestball_outfsys { get; set; }
        public int[]? wzx_netball_downinfsys { get; set; }
        public int[]? wzx_netball_infsys { get; set; }
        public int[]? wzx_netball_openfsys { get; set; }
        public int[]? wzx_netball_outfsys { get; set; }
        public int[]? wzx_nidogeri_attackfsys { get; set; }
        public int[]? wzx_nidogeri_damagefsys { get; set; }
        public int[]? wzx_nighthead_attackfsys { get; set; }
        public int[]? wzx_nighthead_damagefsys { get; set; }
        public int[]? wzx_nihonbare_attackfsys { get; set; }
        public int[]? wzx_nihonbare_kabigonfsys { get; set; }
        public int[]? wzx_nihonbare_powalen_ffsys { get; set; }
        public int[]? wzx_niramitukeru_attackfsys { get; set; }
        public int[]? wzx_noeffect_allfsys { get; set; }
        public int[]? wzx_noeffect_attackfsys { get; set; }
        public int[]? wzx_noeffect_damagefsys { get; set; }
        public int[]? wzx_noeffect_kimefsys { get; set; }
        public int[]? wzx_nomikomu_sp1fsys { get; set; }
        public int[]? wzx_nomikomu_sp2fsys { get; set; }
        public int[]? wzx_nomikomu_specialfsys { get; set; }
        public int[]? wzx_nomikomu_special2fsys { get; set; }
        public int[]? wzx_noroi_attackfsys { get; set; }
        public int[]? wzx_noroi_damagefsys { get; set; }
        public int[]? wzx_noroi_sp1fsys { get; set; }
        public int[]? wzx_noroi_statusfsys { get; set; }
        public int[]? wzx_noshikakari_attackfsys { get; set; }
        public int[]? wzx_noshikakari_bangirasfsys { get; set; }
        public int[]? wzx_noshikakari_damagefsys { get; set; }
        public int[]? wzx_noshikakari_nyoromofsys { get; set; }
        public int[]? wzx_noshikakari_sidonfsys { get; set; }
        public int[]? wzx_odateru_attackfsys { get; set; }
        public int[]? wzx_odateru_damagefsys { get; set; }
        public int[]? wzx_odorokasu_attackfsys { get; set; }
        public int[]? wzx_odorokasu_damagefsys { get; set; }
        public int[]? wzx_oiuti_attackfsys { get; set; }
        public int[]? wzx_oiuti_damagefsys { get; set; }
        public int[]? wzx_oiuti_damage2fsys { get; set; }
        public int[]? wzx_oiuti_onidrillfsys { get; set; }
        public int[]? wzx_oiuti_samayourufsys { get; set; }
        public int[]? wzx_oiuti_sp1fsys { get; set; }
        public int[]? wzx_okimiyage_attackfsys { get; set; }
        public int[]? wzx_okutanhou_attackfsys { get; set; }
        public int[]? wzx_okutanhou_damagefsys { get; set; }
        public int[]? wzx_ongaeshi_attackfsys { get; set; }
        public int[]? wzx_ongaeshi_damagefsys { get; set; }
        public int[]? wzx_ongaeshi_damage2fsys { get; set; }
        public int[]? wzx_ongaeshi_damage3fsys { get; set; }
        public int[]? wzx_ongaeshi_damage4fsys { get; set; }
        public int[]? wzx_onibi_attackfsys { get; set; }
        public int[]? wzx_onibi_damagefsys { get; set; }
        public int[]? wzx_onnen_attackfsys { get; set; }
        public int[]? wzx_onnen_sp1fsys { get; set; }
        public int[]? wzx_oufuku_attackfsys { get; set; }
        public int[]? wzx_oufuku_damagefsys { get; set; }
        public int[]? wzx_oumugaesi_attackfsys { get; set; }
        public int[]? wzx_oumugaesi_damagefsys { get; set; }
        public int[]? wzx_ourorabeam_attackfsys { get; set; }
        public int[]? wzx_ourorabeam_damagefsys { get; set; }
        public int[]? wzx_overheat_attackfsys { get; set; }
        public int[]? wzx_overheat_damagefsys { get; set; }
        public int[]? wzx_piyopiyo_attackfsys { get; set; }
        public int[]? wzx_piyopiyo_damagefsys { get; set; }
        public int[]? wzx_poisontail_attackfsys { get; set; }
        public int[]? wzx_poisontail_damagefsys { get; set; }
        public int[]? wzx_powa_change_ffsys { get; set; }
        public int[]? wzx_powa_change_ifsys { get; set; }
        public int[]? wzx_powa_change_nfsys { get; set; }
        public int[]? wzx_powa_change_startfsys { get; set; }
        public int[]? wzx_powa_change_wfsys { get; set; }
        public int[]? wzx_present_00fsys { get; set; }
        public int[]? wzx_present_01fsys { get; set; }
        public int[]? wzx_present_attackfsys { get; set; }
        public int[]? wzx_present_damagefsys { get; set; }
        public int[]? wzx_present_damage2fsys { get; set; }
        public int[]? wzx_present_purinfsys { get; set; }
        public int[]? wzx_present_sp1fsys { get; set; }
        public int[]? wzx_psyche_attackfsys { get; set; }
        public int[]? wzx_psyche_damagefsys { get; set; }
        public int[]? wzx_psychoboost_attackfsys { get; set; }
        public int[]? wzx_psychoboost_damagefsys { get; set; }
        public int[]? wzx_psychowave_attackfsys { get; set; }
        public int[]? wzx_psychowave_damagefsys { get; set; }
        public int[]? wzx_psycho_attackfsys { get; set; }
        public int[]? wzx_psycho_damagefsys { get; set; }
        public int[]? wzx_psycho_sp1fsys { get; set; }
        public int[]? wzx_puremiyaball_downinfsys { get; set; }
        public int[]? wzx_puremiyaball_infsys { get; set; }
        public int[]? wzx_puremiyaball_openfsys { get; set; }
        public int[]? wzx_puremiyaball_outfsys { get; set; }
        public int[]? wzx_purpleup_statusfsys { get; set; }
        public int[]? wzx_rarepokefsys { get; set; }
        public int[]? wzx_recycle_specialfsys { get; set; }
        public int[]? wzx_reddown_statusfsys { get; set; }
        public int[]? wzx_redup_statusfsys { get; set; }
        public int[]? wzx_reflector_specialfsys { get; set; }
        public int[]? wzx_refresh_specialfsys { get; set; }
        public int[]? wzx_reitoubeam_attackfsys { get; set; }
        public int[]? wzx_reitoubeam_damagefsys { get; set; }
        public int[]? wzx_reitoubeam_damage_sp1fsys { get; set; }
        public int[]? wzx_reitoubeam_kentaurosfsys { get; set; }
        public int[]? wzx_reitoupanchi_attackfsys { get; set; }
        public int[]? wzx_reitoupanchi_damagefsys { get; set; }
        public int[]? wzx_relive_01fsys { get; set; }
        public int[]? wzx_relive_02fsys { get; set; }
        public int[]? wzx_relive_03fsys { get; set; }
        public int[]? wzx_relive_celebi_appearfsys { get; set; }
        public int[]? wzx_relive_celebi_trailfsys { get; set; }
        public int[]? wzx_relive_mainfsys { get; set; }
        public int[]? wzx_relive_main_pigeonfsys { get; set; }
        public int[]? wzx_renzokugiri_attackfsys { get; set; }
        public int[]? wzx_renzokugiri_attack2fsys { get; set; }
        public int[]? wzx_renzokugiri_attack3fsys { get; set; }
        public int[]? wzx_renzokugiri_attack4fsys { get; set; }
        public int[]? wzx_renzokugiri_attack5fsys { get; set; }
        public int[]? wzx_renzokugiri_damagefsys { get; set; }
        public int[]? wzx_renzokugiri_damage2fsys { get; set; }
        public int[]? wzx_renzokugiri_damage3fsys { get; set; }
        public int[]? wzx_renzokugiri_damage4fsys { get; set; }
        public int[]? wzx_renzokugiri_damage5fsys { get; set; }
        public int[]? wzx_renzokugiri_SPfsys { get; set; }
        public int[]? wzx_renzokugiri_SP2fsys { get; set; }
        public int[]? wzx_renzokugiri_SP3fsys { get; set; }
        public int[]? wzx_renzokugiri_SP4fsys { get; set; }
        public int[]? wzx_renzokugiri_strikefsys { get; set; }
        public int[]? wzx_renzokugiri_strike2fsys { get; set; }
        public int[]? wzx_renzokugiri_strike3fsys { get; set; }
        public int[]? wzx_renzokugiri_strike4fsys { get; set; }
        public int[]? wzx_renzokugiri_strike5fsys { get; set; }
        public int[]? wzx_renzoku_attackfsys { get; set; }
        public int[]? wzx_renzoku_damagefsys { get; set; }
        public int[]? wzx_repeatball_downinfsys { get; set; }
        public int[]? wzx_repeatball_infsys { get; set; }
        public int[]? wzx_repeatball_openfsys { get; set; }
        public int[]? wzx_repeatball_outfsys { get; set; }
        public int[]? wzx_revenge_attackfsys { get; set; }
        public int[]? wzx_revenge_damagefsys { get; set; }
        public int[]? wzx_revenge_kairikyfsys { get; set; }
        public int[]? wzx_rockblast_attackfsys { get; set; }
        public int[]? wzx_rockblast_damagefsys { get; set; }
        public int[]? wzx_rockblast_golonefsys { get; set; }
        public int[]? wzx_rocket_attackfsys { get; set; }
        public int[]? wzx_rocket_damagefsys { get; set; }
        public int[]? wzx_rocket_specialfsys { get; set; }
        public int[]? wzx_rocket_special_sp1fsys { get; set; }
        public int[]? wzx_ryunoibuki_attackfsys { get; set; }
        public int[]? wzx_ryunoibuki_damagefsys { get; set; }
        public int[]? wzx_ryunoibuki_kairyufsys { get; set; }
        public int[]? wzx_ryunoikari_attackfsys { get; set; }
        public int[]? wzx_ryunoikari_damagefsys { get; set; }
        public int[]? wzx_ryunoikari_sp1fsys { get; set; }
        public int[]? wzx_ryunomai_gyaradosfsys { get; set; }
        public int[]? wzx_ryunomai_specialfsys { get; set; }
        public int[]? wzx_S3_event_hibana_01fsys { get; set; }
        public int[]? wzx_S3_event_hibana_02fsys { get; set; }
        public int[]? wzx_S3_out_thunder_01fsys { get; set; }
        public int[]? wzx_safariball_downinfsys { get; set; }
        public int[]? wzx_safariball_infsys { get; set; }
        public int[]? wzx_safariball_openfsys { get; set; }
        public int[]? wzx_safariball_outfsys { get; set; }
        public int[]? wzx_saimin_attackfsys { get; set; }
        public int[]? wzx_saimin_damagefsys { get; set; }
        public int[]? wzx_saimin_odoshishifsys { get; set; }
        public int[]? wzx_saimin_sp1fsys { get; set; }
        public int[]? wzx_sawagu_attackfsys { get; set; }
        public int[]? wzx_sawagu_damagefsys { get; set; }
        public int[]? wzx_sawagu_sp1fsys { get; set; }
        public int[]? wzx_seinaru_attackfsys { get; set; }
        public int[]? wzx_seinaru_damagefsys { get; set; }
        public int[]? wzx_seityou_specialfsys { get; set; }
        public int[]? wzx_seityou_utsubotfsys { get; set; }
        public int[]? wzx_selfdamagefsys { get; set; }
        public int[]? wzx_shadowball_attackfsys { get; set; }
        public int[]? wzx_shadowball_damagefsys { get; set; }
        public int[]? wzx_shadowpunch_attackfsys { get; set; }
        public int[]? wzx_shadowpunch_damagefsys { get; set; }
        public int[]? wzx_shibire_attackfsys { get; set; }
        public int[]? wzx_shibire_damagefsys { get; set; }
        public int[]? wzx_shibire_sp1fsys { get; set; }
        public int[]? wzx_shimetsukeru_attackfsys { get; set; }
        public int[]? wzx_shimetsukeru_damagefsys { get; set; }
        public int[]? wzx_shimetsukeru_sp1fsys { get; set; }
        public int[]? wzx_shinsoku_attackfsys { get; set; }
        public int[]? wzx_shinsoku_damagefsys { get; set; }
        public int[]? wzx_shippowofuru_attackfsys { get; set; }
        public int[]? wzx_shippowofuru_eievuifsys { get; set; }
        public int[]? wzx_shippowofuru_enekororofsys { get; set; }
        public int[]? wzx_shippowofuru_showersfsys { get; set; }
        public int[]? wzx_shippowofuru_sp1fsys { get; set; }
        public int[]? wzx_shiroikiri_specialfsys { get; set; }
        public int[]? wzx_shita_attackfsys { get; set; }
        public int[]? wzx_shita_bulufsys { get; set; }
        public int[]? wzx_shita_damagefsys { get; set; }
        public int[]? wzx_shita_nodatfsys { get; set; }
        public int[]? wzx_shita_sp1fsys { get; set; }
        public int[]? wzx_shizennochikara_attackfsys { get; set; }
        public int[]? wzx_shizennochikara_damagefsys { get; set; }
        public int[]? wzx_signalbeam_attackfsys { get; set; }
        public int[]? wzx_signalbeam_damagefsys { get; set; }
        public int[]? wzx_signalbeam_kongpangfsys { get; set; }
        public int[]? wzx_sinpi_lunatonefsys { get; set; }
        public int[]? wzx_sinpi_specialfsys { get; set; }
        public int[]? wzx_siofuki_attackfsys { get; set; }
        public int[]? wzx_siofuki_damagefsys { get; set; }
        public int[]? wzx_siofuki_sp1fsys { get; set; }
        public int[]? wzx_sketch_attackfsys { get; set; }
        public int[]? wzx_sketch_damagefsys { get; set; }
        public int[]? wzx_sketch_doblefsys { get; set; }
        public int[]? wzx_sketch_specialfsys { get; set; }
        public int[]? wzx_skillswap_attackfsys { get; set; }
        public int[]? wzx_skillswap_damagefsys { get; set; }
        public int[]? wzx_skillswap_damage_sp1fsys { get; set; }
        public int[]? wzx_skillswap_kongpangfsys { get; set; }
        public int[]? wzx_skillswap_sp1fsys { get; set; }
        public int[]? wzx_skillswap_specialfsys { get; set; }
        public int[]? wzx_skillswap_special_sp1fsys { get; set; }
        public int[]? wzx_skyupper_attackfsys { get; set; }
        public int[]? wzx_skyupper_damagefsys { get; set; }
        public int[]? wzx_skyupper_ebiwalarfsys { get; set; }
        public int[]? wzx_smog_attackfsys { get; set; }
        public int[]? wzx_smog_damagefsys { get; set; }
        public int[]? wzx_snatch_attackfsys { get; set; }
        public int[]? wzx_snatch_attack_divefsys { get; set; }
        public int[]? wzx_snatch_attack_gorgeusfsys { get; set; }
        public int[]? wzx_snatch_attack_hyperfsys { get; set; }
        public int[]? wzx_snatch_attack_masterfsys { get; set; }
        public int[]? wzx_snatch_attack_monsterfsys { get; set; }
        public int[]? wzx_snatch_attack_nestfsys { get; set; }
        public int[]? wzx_snatch_attack_netfsys { get; set; }
        public int[]? wzx_snatch_attack_premirefsys { get; set; }
        public int[]? wzx_snatch_attack_repeatfsys { get; set; }
        public int[]? wzx_snatch_attack_safarifsys { get; set; }
        public int[]? wzx_snatch_attack_superfsys { get; set; }
        public int[]? wzx_snatch_attack_timerfsys { get; set; }
        public int[]? wzx_snatch_ball_landfsys { get; set; }
        public int[]? wzx_snatch_ball_land_divefsys { get; set; }
        public int[]? wzx_snatch_ball_land_gorgeusfsys { get; set; }
        public int[]? wzx_snatch_ball_land_hyperfsys { get; set; }
        public int[]? wzx_snatch_ball_land_masterfsys { get; set; }
        public int[]? wzx_snatch_ball_land_monsterfsys { get; set; }
        public int[]? wzx_snatch_ball_land_nestfsys { get; set; }
        public int[]? wzx_snatch_ball_land_netfsys { get; set; }
        public int[]? wzx_snatch_ball_land_premirefsys { get; set; }
        public int[]? wzx_snatch_ball_land_repeatfsys { get; set; }
        public int[]? wzx_snatch_ball_land_safarifsys { get; set; }
        public int[]? wzx_snatch_ball_land_superfsys { get; set; }
        public int[]? wzx_snatch_ball_land_timerfsys { get; set; }
        public int[]? wzx_snatch_missfsys { get; set; }
        public int[]? wzx_snatch_miss_divefsys { get; set; }
        public int[]? wzx_snatch_miss_gorgeusfsys { get; set; }
        public int[]? wzx_snatch_miss_hyperfsys { get; set; }
        public int[]? wzx_snatch_miss_masterfsys { get; set; }
        public int[]? wzx_snatch_miss_monsterfsys { get; set; }
        public int[]? wzx_snatch_miss_nestfsys { get; set; }
        public int[]? wzx_snatch_miss_netfsys { get; set; }
        public int[]? wzx_snatch_miss_premirefsys { get; set; }
        public int[]? wzx_snatch_miss_repeatfsys { get; set; }
        public int[]? wzx_snatch_miss_safarifsys { get; set; }
        public int[]? wzx_snatch_miss_superfsys { get; set; }
        public int[]? wzx_snatch_miss_timerfsys { get; set; }
        public int[]? wzx_snatch_poke_outfsys { get; set; }
        public int[]? wzx_snatch_shakefsys { get; set; }
        public int[]? wzx_snatch_shake_divefsys { get; set; }
        public int[]? wzx_snatch_shake_gorgeusfsys { get; set; }
        public int[]? wzx_snatch_shake_hyperfsys { get; set; }
        public int[]? wzx_snatch_shake_masterfsys { get; set; }
        public int[]? wzx_snatch_shake_monsterfsys { get; set; }
        public int[]? wzx_snatch_shake_nestfsys { get; set; }
        public int[]? wzx_snatch_shake_netfsys { get; set; }
        public int[]? wzx_snatch_shake_premirefsys { get; set; }
        public int[]? wzx_snatch_shake_repeatfsys { get; set; }
        public int[]? wzx_snatch_shake_safarifsys { get; set; }
        public int[]? wzx_snatch_shake_superfsys { get; set; }
        public int[]? wzx_snatch_shake_timerfsys { get; set; }
        public int[]? wzx_snatch_snatchfsys { get; set; }
        public int[]? wzx_solarbeam_attackfsys { get; set; }
        public int[]? wzx_solarbeam_barubeatfsys { get; set; }
        public int[]? wzx_solarbeam_damagefsys { get; set; }
        public int[]? wzx_solarbeam_eipamfsys { get; set; }
        public int[]? wzx_solarbeam_kentaurosfsys { get; set; }
        public int[]? wzx_solarbeam_sp1fsys { get; set; }
        public int[]? wzx_solarbeam_specialfsys { get; set; }
        public int[]? wzx_solarbeam_special_sp1fsys { get; set; }
        public int[]? wzx_sonicboom_ariadosfsys { get; set; }
        public int[]? wzx_sonicboom_attackfsys { get; set; }
        public int[]? wzx_sonicboom_damagefsys { get; set; }
        public int[]? wzx_sonicboom_rarecoilfsys { get; set; }
        public int[]? wzx_sorawotobu_attackfsys { get; set; }
        public int[]? wzx_sorawotobu_damagefsys { get; set; }
        public int[]? wzx_sorawotobu_sp1fsys { get; set; }
        public int[]? wzx_sorawotobu_sp2fsys { get; set; }
        public int[]? wzx_sorawotobu_specialfsys { get; set; }
        public int[]? wzx_spark_attackfsys { get; set; }
        public int[]? wzx_spark_damagefsys { get; set; }
        public int[]? wzx_speedstar_attackfsys { get; set; }
        public int[]? wzx_speedstar_damagefsys { get; set; }
        public int[]? wzx_speedstar_sp1fsys { get; set; }
        public int[]? wzx_spoonmage_attackfsys { get; set; }
        public int[]? wzx_spoonmage_foodinfsys { get; set; }
        public int[]? wzx_spoonmage_yungerefsys { get; set; }
        public int[]? wzx_suitoru_attackfsys { get; set; }
        public int[]? wzx_suitoru_damagefsys { get; set; }
        public int[]? wzx_suitoru_nazokokusafsys { get; set; }
        public int[]? wzx_suitoru_sp1fsys { get; set; }
        public int[]? wzx_suitoru_specialfsys { get; set; }
        public int[]? wzx_sunaarashi_allfsys { get; set; }
        public int[]? wzx_sunaarashi_attackfsys { get; set; }
        public int[]? wzx_sunaarashi_damagefsys { get; set; }
        public int[]? wzx_sunaarashi_sp1fsys { get; set; }
        public int[]? wzx_sunaarashi_sp2fsys { get; set; }
        public int[]? wzx_sunajigoku_attackfsys { get; set; }
        public int[]? wzx_sunajigoku_damagefsys { get; set; }
        public int[]? wzx_sunakake_attackfsys { get; set; }
        public int[]? wzx_sunakake_damagefsys { get; set; }
        public int[]? wzx_sunakake_sp1fsys { get; set; }
        public int[]? wzx_sunakake_sp2fsys { get; set; }
        public int[]? wzx_sunakake_sp3fsys { get; set; }
        public int[]? wzx_superball_downinfsys { get; set; }
        public int[]? wzx_superball_infsys { get; set; }
        public int[]? wzx_superball_openfsys { get; set; }
        public int[]? wzx_superball_outfsys { get; set; }
        public int[]? wzx_sutemi_attackfsys { get; set; }
        public int[]? wzx_sutemi_damagefsys { get; set; }
        public int[]? wzx_taiatari_attackfsys { get; set; }
        public int[]? wzx_taiatari_damagefsys { get; set; }
        public int[]? wzx_taki_attackfsys { get; set; }
        public int[]? wzx_taki_damagefsys { get; set; }
        public int[]? wzx_taki_milokarossfsys { get; set; }
        public int[]? wzx_takuwaeru_specialfsys { get; set; }
        public int[]? wzx_tamagobomb_attackfsys { get; set; }
        public int[]? wzx_tamagobomb_damagefsys { get; set; }
        public int[]? wzx_tamagobomb_luckyfsys { get; set; }
        public int[]? wzx_tamagobomb_nassyfsys { get; set; }
        public int[]? wzx_tamagoumi_mewfsys { get; set; }
        public int[]? wzx_tamagoumi_sp1fsys { get; set; }
        public int[]? wzx_tamagoumi_specialfsys { get; set; }
        public int[]? wzx_tamanage_attackfsys { get; set; }
        public int[]? wzx_tamanage_damagefsys { get; set; }
        public int[]? wzx_tamanage_nassyfsys { get; set; }
        public int[]? wzx_tane_attackfsys { get; set; }
        public int[]? wzx_tane_damagefsys { get; set; }
        public int[]? wzx_tane_sp1fsys { get; set; }
        public int[]? wzx_tataki_attackfsys { get; set; }
        public int[]? wzx_tataki_damagefsys { get; set; }
        public int[]? wzx_tataki_sp1fsys { get; set; }
        public int[]? wzx_tatsumaki_attackfsys { get; set; }
        public int[]? wzx_tatsumaki_camomefsys { get; set; }
        public int[]? wzx_tatsumaki_damagefsys { get; set; }
        public int[]? wzx_tatsumaki_sp1fsys { get; set; }
        public int[]? wzx_tedasuke_attackfsys { get; set; }
        public int[]? wzx_tedasuke_sp1fsys { get; set; }
        public int[]? wzx_tedasuke_specialfsys { get; set; }
        public int[]? wzx_tedasuke_statusfsys { get; set; }
        public int[]? wzx_teleport_specialfsys { get; set; }
        public int[]? wzx_tenshinokiss_attackfsys { get; set; }
        public int[]? wzx_tenshinokiss_damagefsys { get; set; }
        public int[]? wzx_tenshinokiss_sp1fsys { get; set; }
        public int[]? wzx_teppeki_cotoisefsys { get; set; }
        public int[]? wzx_teppeki_specialfsys { get; set; }
        public int[]? wzx_texture2_specialfsys { get; set; }
        public int[]? wzx_texture_specialfsys { get; set; }
        public int[]? wzx_throw_divefsys { get; set; }
        public int[]? wzx_throw_gorgeousfsys { get; set; }
        public int[]? wzx_throw_gorgeusfsys { get; set; }
        public int[]? wzx_throw_hyperfsys { get; set; }
        public int[]? wzx_throw_masterfsys { get; set; }
        public int[]? wzx_throw_monsterfsys { get; set; }
        public int[]? wzx_throw_nestfsys { get; set; }
        public int[]? wzx_throw_netfsys { get; set; }
        public int[]? wzx_throw_premierefsys { get; set; }
        public int[]? wzx_throw_repeatfsys { get; set; }
        public int[]? wzx_throw_safarifsys { get; set; }
        public int[]? wzx_throw_superfsys { get; set; }
        public int[]? wzx_throw_timerfsys { get; set; }
        public int[]? wzx_tiisakunaru_specialfsys { get; set; }
        public int[]? wzx_timerball_downinfsys { get; set; }
        public int[]? wzx_timerball_infsys { get; set; }
        public int[]? wzx_timerball_openfsys { get; set; }
        public int[]? wzx_timerball_outfsys { get; set; }
        public int[]? wzx_tobigeri_attackfsys { get; set; }
        public int[]? wzx_tobigeri_damagefsys { get; set; }
        public int[]? wzx_tobihaneru_attackfsys { get; set; }
        public int[]? wzx_tobihaneru_damagefsys { get; set; }
        public int[]? wzx_tobihaneru_specialfsys { get; set; }
        public int[]? wzx_tobihaneru_special_sp1fsys { get; set; }
        public int[]? wzx_tobihiza_attackfsys { get; set; }
        public int[]? wzx_tobihiza_damagefsys { get; set; }
        public int[]? wzx_togekyanon_attackfsys { get; set; }
        public int[]? wzx_togekyanon_damagefsys { get; set; }
        public int[]? wzx_togekyanon_parshenfsys { get; set; }
        public int[]? wzx_tokerufsys { get; set; }
        public int[]? wzx_tokeru_specialfsys { get; set; }
        public int[]? wzx_tooboe_sp1fsys { get; set; }
        public int[]? wzx_tooboe_specialfsys { get; set; }
        public int[]? wzx_toosenbou_attackfsys { get; set; }
        public int[]? wzx_toosenbou_damagefsys { get; set; }
        public int[]? wzx_tosshin_attackfsys { get; set; }
        public int[]? wzx_tosshin_damagefsys { get; set; }
        public int[]? wzx_tosshin_sp1fsys { get; set; }
        public int[]? wzx_trainer_enter_afsys { get; set; }
        public int[]? wzx_trainer_enter_bfsys { get; set; }
        public int[]? wzx_trainer_enter_cfsys { get; set; }
        public int[]? wzx_trainer_enter_dfsys { get; set; }
        public int[]? wzx_trainer_enter_efsys { get; set; }
        public int[]? wzx_trick_attackfsys { get; set; }
        public int[]? wzx_trick_barubeatfsys { get; set; }
        public int[]? wzx_trick_damagefsys { get; set; }
        public int[]? wzx_trick_damage_sp1fsys { get; set; }
        public int[]? wzx_trick_foodinfsys { get; set; }
        public int[]? wzx_trick_specialfsys { get; set; }
        public int[]? wzx_trick_special_sp1fsys { get; set; }
        public int[]? wzx_triplekick_attackfsys { get; set; }
        public int[]? wzx_triplekick_damagefsys { get; set; }
        public int[]? wzx_triplekick_damage2fsys { get; set; }
        public int[]? wzx_triplekick_damage3fsys { get; set; }
        public int[]? wzx_tryattack_attackfsys { get; set; }
        public int[]? wzx_tryattack_damagefsys { get; set; }
        public int[]? wzx_tryattack_porygonfsys { get; set; }
        public int[]? wzx_tsubame_attackfsys { get; set; }
        public int[]? wzx_tsubame_damagefsys { get; set; }
        public int[]? wzx_tsubasa_attackfsys { get; set; }
        public int[]? wzx_tsubasa_damagefsys { get; set; }
        public int[]? wzx_tsunodrillk_doblefsys { get; set; }
        public int[]? wzx_tsunodrill_attackfsys { get; set; }
        public int[]? wzx_tsunodrill_damagefsys { get; set; }
        public int[]? wzx_tsunodrill_kentaurosfsys { get; set; }
        public int[]? wzx_tsunodrill_laplacefsys { get; set; }
        public int[]? wzx_tsunodrill_sp1fsys { get; set; }
        public int[]? wzx_tsuno_attackfsys { get; set; }
        public int[]? wzx_tsuno_damagefsys { get; set; }
        public int[]? wzx_tsuppari_attackfsys { get; set; }
        public int[]? wzx_tsuppari_damagefsys { get; set; }
        public int[]? wzx_tsuru_attackfsys { get; set; }
        public int[]? wzx_tsuru_damagefsys { get; set; }
        public int[]? wzx_tsuru_fushigibanafsys { get; set; }
        public int[]? wzx_tsuru_sp1fsys { get; set; }
        public int[]? wzx_tsutsuku_attackfsys { get; set; }
        public int[]? wzx_tsutsuku_azumaofsys { get; set; }
        public int[]? wzx_tsutsuku_damagefsys { get; set; }
        public int[]? wzx_tsutsuku_nidokingfsys { get; set; }
        public int[]? wzx_tukinohikari_specialfsys { get; set; }
        public int[]? wzx_turarabari_attackfsys { get; set; }
        public int[]? wzx_turarabari_damagefsys { get; set; }
        public int[]? wzx_turarabari_parshenfsys { get; set; }
        public int[]? wzx_turuginomai_specialfsys { get; set; }
        public int[]? wzx_turuginomai_strikefsys { get; set; }
        public int[]? wzx_tyouonpa_attackfsys { get; set; }
        public int[]? wzx_tyouonpa_damagefsys { get; set; }
        public int[]? wzx_tyouonpa_sp1fsys { get; set; }
        public int[]? wzx_urami_attackfsys { get; set; }
        public int[]? wzx_urami_damagefsys { get; set; }
        public int[]? wzx_usonaki_attackfsys { get; set; }
        public int[]? wzx_usonaki_kucheatfsys { get; set; }
        public int[]? wzx_utau_attackfsys { get; set; }
        public int[]? wzx_utau_sp1fsys { get; set; }
        public int[]? wzx_utau_tylttofsys { get; set; }
        public int[]? wzx_uzusio_attackfsys { get; set; }
        public int[]? wzx_uzusio_damagefsys { get; set; }
        public int[]? wzx_version_out_attackfsys { get; set; }
        public int[]? wzx_version_out_damagefsys { get; set; }
        public int[]? wzx_voltecker_attackfsys { get; set; }
        public int[]? wzx_voltecker_damagefsys { get; set; }
        public int[]? wzx_wakeupfsys { get; set; }
        public int[]? wzx_waruagaki_attackfsys { get; set; }
        public int[]? wzx_waruagaki_damagefsys { get; set; }
        public int[]? wzx_wata_attackfsys { get; set; }
        public int[]? wzx_wata_damagefsys { get; set; }
        public int[]? wzx_weatherball_attackfsys { get; set; }
        public int[]? wzx_weatherball_damagefsys { get; set; }
        public int[]? wzx_weatherball_damage_amefsys { get; set; }
        public int[]? wzx_weatherball_damage_ararefsys { get; set; }
        public int[]? wzx_weatherball_damage_darkfsys { get; set; }
        public int[]? wzx_weatherball_damage_harefsys { get; set; }
        public int[]? wzx_weatherball_damage_sunafsys { get; set; }
        public int[]? wzx_winfsys { get; set; }
        public int[]? wzx_yadorigi_attackfsys { get; set; }
        public int[]? wzx_yadorigi_damagefsys { get; set; }
        public int[]? wzx_yadorigi_sp1fsys { get; set; }
        public int[]? wzx_yadorigi_statusfsys { get; set; }
        public int[]? wzx_yakedo_statusfsys { get; set; }
        public int[]? wzx_yasei_ball_land_divefsys { get; set; }
        public int[]? wzx_yasei_ball_land_gorgeusfsys { get; set; }
        public int[]? wzx_yasei_ball_land_hyperfsys { get; set; }
        public int[]? wzx_yasei_ball_land_masterfsys { get; set; }
        public int[]? wzx_yasei_ball_land_monsterfsys { get; set; }
        public int[]? wzx_yasei_ball_land_nestfsys { get; set; }
        public int[]? wzx_yasei_ball_land_netfsys { get; set; }
        public int[]? wzx_yasei_ball_land_premirefsys { get; set; }
        public int[]? wzx_yasei_ball_land_repeatfsys { get; set; }
        public int[]? wzx_yasei_ball_land_safarifsys { get; set; }
        public int[]? wzx_yasei_ball_land_superfsys { get; set; }
        public int[]? wzx_yasei_ball_land_timerfsys { get; set; }
        public int[]? wzx_yasei_getfsys { get; set; }
        public int[]? wzx_yasei_get_divefsys { get; set; }
        public int[]? wzx_yasei_get_gorgeusfsys { get; set; }
        public int[]? wzx_yasei_get_hyperfsys { get; set; }
        public int[]? wzx_yasei_get_masterfsys { get; set; }
        public int[]? wzx_yasei_get_monsterfsys { get; set; }
        public int[]? wzx_yasei_get_nestfsys { get; set; }
        public int[]? wzx_yasei_get_netfsys { get; set; }
        public int[]? wzx_yasei_get_premirefsys { get; set; }
        public int[]? wzx_yasei_get_repeatfsys { get; set; }
        public int[]? wzx_yasei_get_safarifsys { get; set; }
        public int[]? wzx_yasei_get_superfsys { get; set; }
        public int[]? wzx_yasei_get_timerfsys { get; set; }
        public int[]? wzx_yasei_poke_outfsys { get; set; }
        public int[]? wzx_yasei_poke_out_divefsys { get; set; }
        public int[]? wzx_yasei_poke_out_gorgeusfsys { get; set; }
        public int[]? wzx_yasei_poke_out_hyperfsys { get; set; }
        public int[]? wzx_yasei_poke_out_monsterfsys { get; set; }
        public int[]? wzx_yasei_poke_out_nestfsys { get; set; }
        public int[]? wzx_yasei_poke_out_netfsys { get; set; }
        public int[]? wzx_yasei_poke_out_premirefsys { get; set; }
        public int[]? wzx_yasei_poke_out_repeatfsys { get; set; }
        public int[]? wzx_yasei_poke_out_safarifsys { get; set; }
        public int[]? wzx_yasei_poke_out_superfsys { get; set; }
        public int[]? wzx_yasei_poke_out_timerfsys { get; set; }
        public int[]? wzx_yasei_shake_divefsys { get; set; }
        public int[]? wzx_yasei_shake_gorgeusfsys { get; set; }
        public int[]? wzx_yasei_shake_hyperfsys { get; set; }
        public int[]? wzx_yasei_shake_masterfsys { get; set; }
        public int[]? wzx_yasei_shake_monsterfsys { get; set; }
        public int[]? wzx_yasei_shake_nestfsys { get; set; }
        public int[]? wzx_yasei_shake_netfsys { get; set; }
        public int[]? wzx_yasei_shake_premirefsys { get; set; }
        public int[]? wzx_yasei_shake_repeatfsys { get; set; }
        public int[]? wzx_yasei_shake_safarifsys { get; set; }
        public int[]? wzx_yasei_shake_superfsys { get; set; }
        public int[]? wzx_yasei_shake_timerfsys { get; set; }
        public int[]? wzx_yatsuatari_attackfsys { get; set; }
        public int[]? wzx_yatsuatari_damagefsys { get; set; }
        public int[]? wzx_yatsuatari_damage2fsys { get; set; }
        public int[]? wzx_yatsuatari_damage3fsys { get; set; }
        public int[]? wzx_yatsuatari_damage4fsys { get; set; }
        public int[]? wzx_yoga_sleeperfsys { get; set; }
        public int[]? wzx_yoga_specialfsys { get; set; }
        public int[]? wzx_yokodori_attackfsys { get; set; }
        public int[]? wzx_yokodori_damagefsys { get; set; }
        public int[]? wzx_yokodori_eipamfsys { get; set; }
        public int[]? wzx_yokodori_sp1fsys { get; set; }
        public int[]? wzx_yokodori_specialfsys { get; set; }
        public int[]? wzx_youkaieki_attackfsys { get; set; }
        public int[]? wzx_youkaieki_damagefsys { get; set; }
        public int[]? wzx_yubiwofuru_attackfsys { get; set; }
        public int[]? wzx_yubiwofuru_kabigonfsys { get; set; }
        public int[]? wzx_yubiwofuru_sp1fsys { get; set; }
        public int[]? wzx_yubiwofuru_sp2fsys { get; set; }
        public int[]? wzx_yumekui_attackfsys { get; set; }
        public int[]? wzx_yumekui_damagefsys { get; set; }
        public int[]? wzx_yumekui_sp1fsys { get; set; }
        public int[]? wzx_yumekui_sp2fsys { get; set; }
        public int[]? wzx_yumekui_specialfsys { get; set; }
        public int[]? wzx_zettaireido_attackfsys { get; set; }
        public int[]? wzx_zettaireido_damagefsys { get; set; }
        public int[]? wzx_ziware_attackfsys { get; set; }
        public int[]? wzx_ziware_damagefsys { get; set; }
        public int[]? wzx_ziware_sp1fsys { get; set; }
        public int[]? wzx_zutsuki_attackfsys { get; set; }
        public int[]? wzx_zutsuki_bossgodorafsys { get; set; }
        public int[]? wzx_zutsuki_damagefsys { get; set; }
    }
}